### ISSUE TITLE
Analýza bludiska

### ISSUE THREAD

**Issue by kachalavova1** [kachalavova1/UDS2#2]
Treba zanalyzovať bludisko - jeho súradnice a približnú veľkosť. V špecifikácií aplikácie nie je jasne definované, ako by malo bludisko vyzerať, môžeš sa teda potom buď inšpirovať už existujúcou hrou alebo byť kreatívna a pokúsiť sa vymyslieť vlastné.

**Comment by Nikol112** [comment]
Analýza bludiska:
Bludisko sa skladá z obdĺžnikových stien, ktoré sú zadefinované na osy (x) a osy (y). Pac-Man cez tieto steny nebude prechádzať a bude sa pohybovať pomedzi steny.  Taktiež sa medzi stenami budú nachádzať pointy, ktoré bude zbierať Pac-Man. Pac-Man aby vyhral musí pozbierať všetky pointy medzi stenami.  Tieto steny môžu mať rôzne farby a môžu byť rôzne poukladané  podľa zváženia alebo podľa levelu obťažnosti. Steny by mali mať inú farbu ako je farba pozadia v hre Pac-Man.
