### ISSUE TITLE
Analýza fungovania a pohybu postáv

### ISSUE THREAD

**Issue by kachalavova1** [kachalavova1/UDS2#3]
Prosím, zanalyzuj fungovanie postáv. Herné prostredie obsahuje bludisko, hlavnú postavu ovládanú hráčom Pac-Mana a štyroch duchov ktorí sa náhodne pohybujú - "naháňajú pac-mana".  V špecifikácií je aj zadané že hru treba "obohatiť" o  schopnosti dvoch duchov (Blinky a Clyde). Nakoľko nie je definované o aké schopnosti sa má jednať, je na tebe aby si túto špeciálnu schopnosť vymyslel. Nemusí to byť však nič komplikované, aby sme to potom vedeli aj zrealizovať. Napíš prosím potom nejaký dokument - kde by si to všetko zhrnul. Nezabúdaj že v dokumentácií sú už nejaké jasne dané pravidlá, ktoré postavy musia spĺňať.

**Comment by ghost** [comment]
Analýzu rozdelím na viacero častí:
- Rýchlosť a pohyb v samotnej hre - hra by mohla byť založená na tickoch. Počas každého ticku by mohla každá postava spraviť jeden pohyb. Tick by mohol byť nastavený na 0,125 sec. a mohli by sme použiť naprogramovanú triedu MANAGER, s ktorou sme pracovali na Informatike 1 v 6 týždni cvičení. 
- Pac Man - má byť ovládaný hráčom. K jeho pohybu by sme mohli taktiež použiť triedu manager a posúvanie postavy nastaviť na šipky.
- Duchovia by mali mať náhodné pohybovanie s tým, že by muselo byť vytvorené vetvenie na to, kam sa môžu pohybovať, aby nemohli isť do steny. Najlepšie pomocou IF alebo SWITCH
- Duchovia Blinky a Clyde by mohli mať špeciálnu schopnosť, že by sa hýbali 2 krát rýchlejšie, čiže rýchlosť ich tickov bude 0,0625 sec.
