### ISSUE TITLE
Návrh pohybu postáv 

### ISSUE THREAD

**Issue by kachalavova1** [kachalavova1/UDS2#8]
Je potrebné napísať návrh fungovania postáv. Potom to vložiť do zdielaného súboru na Teamse. Predpokladám, že by si s tým nemal mať vážnejší problém avšak, ak by si mal akékoľvek otázky neváhaj ma kontaktovať.

**Comment by ghost** [comment]
Ahoj, čo sa týka analýzy a spísania textu na fungovanie postav, tak to už som posielal v Issue Analýza postav, ktorú máme closed.
Čo sa týka kódu, tak ten ešte píšem, keď bude dokončený tak ho pushem na server a dám vedieť.

**Comment by kachalavova1** [comment]
Fungovanie by malo 

> Ahoj, čo sa týka analýzy a spísania textu na fungovanie postav, tak to už som posielal v Issue Analýza postav, ktorú máme closed. Čo sa týka kódu, tak ten ešte píšem, keď bude dokončený tak ho pushem na server a dám vedieť.

Ahoj, návrh fungovania postáv by mal byť spísaný samostatne. Ale pozriem sa na to, porpípadne to upravím. Ďakujem.
